### ISSUE TITLE
Header cover hover Popovers

### ISSUE THREAD

**Issue by hhshii** [StylishThemes/GitHub-FixedHeader#15]
* **Browser**:Chrome
* **Operating System**:MacOS
* **Link to page with the issue**:none
* **Screenshot**:

![image](https://user-images.githubusercontent.com/14303098/54102923-4edad400-4405-11e9-9855-e2fea0cafaa1.png)

add higher `z-index`may work to this

```
.Popover {
  z-index: 1001!important;
}
```

**Comment by Mottie** [comment]
Hey @GFwer!

Wow, sorry for taking so long to get back to you. I've fixed this in the latest update.
