### ISSUE TITLE
Sticky sidebar can overlap footer

### ISSUE THREAD

**Issue by joelworsham** [StylishThemes/GitHub-FixedHeader#2]

**Comment by silverwind** [comment]
Note that browser behaviour is quite different on this sidebar. Chrome does not support `position:sticky`, so Github uses a Javascript shim for it. Firefox on the other hand has support for it.

Last I noticed, native `position:sticky` should be in use for Firefox. Also see https://github.com/StylishThemes/GitHub-Dark/commit/28dc922a44107bb5403ee542b6ef8e8ccf528d3e for a fix I attempted when they decided to use the shim in Firefox too.

**Comment by Mottie** [comment]
I didn't notice the sidebar ever overlapping the footer; and I'm using ZenHub which adds a bunch more stuff into that sidebar.

I just updated this style, please check if this is still a problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved.
