### ISSUE TITLE
Overlapping commit details file popup menu

### ISSUE THREAD

**Issue by stonecrusher** [StylishThemes/GitHub-FixedHeader#20]
* **Browser**: FF 72.0.2
* **Operating System**: Win10-1909
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-FixedHeader/commit/9d6a63d47c41a8fc9825ddd357164346dc2f88ba
* **Screenshot**:
![Screenshot_2020-02-11](https://user-images.githubusercontent.com/1388389/74239891-16104280-4cd9-11ea-9923-b25439e8b1a0.png)

1. Minimize the code display by clicking the dropdown arrows on the left
2. Click the three dots on the right

`#files .file-header { position: sticky !important; }` seems to be the culprit.

I used dark style to show it better (unrelated to the problem).

**Comment by the-j0k3r** [comment]
hey @stonecrusher =) I dont use this style, but this file header is already sticky by default when youre scrolling through a bigger file, so maybe just remove it.

**Comment by stonecrusher** [comment]
Hey, long time no see ;-)

>  this file header is already sticky by default

Do you have an example? For me it's not sticky by default.
I'll disable the `@supports (position: sticky) {` section for now as seeing this menu is more important than having the sticky header for each file.

**Comment by xt0rted** [comment]
The only spot file headers are sticky is in PRs. Both the files and commits tabs are like this. Everywhere else the headers aren't sticky.

I have a fix for this. The PR view is a little weird, but that looks to be unrelated to this issue.

**Comment by xt0rted** [comment]
Just released v1.2.18 which fixes this.
