### ISSUE TITLE
Broken dropdown list UI

### ISSUE THREAD

**Issue by altern8tif** [StylishThemes/GitHub-FixedHeader#5]
<img width="404" alt="screen shot 2016-09-16 at 2 50 32 pm" src="https://cloud.githubusercontent.com/assets/5793364/18577548/fe7956f6-7c1c-11e6-9bff-3168ee6abbee.png">

As seen above, the `z-index` needs changing, and less obvious but more crucial, is that the items in the dropdown list become unclickable.

**Comment by Mottie** [comment]
Hi @altern8tif!

This should already be fixed. Try manually updating the Style from userstyles because for some reason it's not getting automatically updated - see https://github.com/JasonBarnabe/stylish-chrome/issues/179.

**Comment by altern8tif** [comment]
Thanks @Mottie
