### ISSUE TITLE
1px gap below header on profile page

### ISSUE THREAD

**Issue by skwerlman** [StylishThemes/GitHub-FixedHeader#7]
![image](https://cloud.githubusercontent.com/assets/6954107/19220662/69d2bdb2-8e00-11e6-8404-b878fe9d5718.png)

**Comment by Mottie** [comment]
Hi @skwerlman!

Interesting that I didn't notice this because I keep GitHub zoomed in at 110% on Chrome. Thanks for reporting it, I'll have it fixed shortly.
