### ISSUE TITLE
[feature request] fold away header

### ISSUE THREAD

**Issue by Riajyuu** [StylishThemes/GitHub-FixedHeader#8]
When the mouse isn't pointing at header area, fold the header up but display it again with mouse hover.
You may add an option to define the delay (I suggest 150ms~250ms) to display the header as mouse hover before someone installs this style from USO.

**Comment by Mottie** [comment]
Hi @EMLVIRUS!

I'll see what I can do... I *think* it might be possible to do with css only, but I'll need to mess around with it a bit.

**Comment by joelworsham** [comment]
Personally I like being able to see the header constantly, this is the idea of it being fixed in the first place. I like, especially, being able to see the notifications icon and search bar.

I suppose my vote would be against this, even though it is a good idea.

**Comment by Mottie** [comment]
@joelworsham I agree... I think a userscript would be required to make this work anyway. I could not find a "nice" css-only solution.

**Comment by Mottie** [comment]
A [GitHub-reveal-header](https://greasyfork.org/en/scripts/30308-github-reveal-header) userscript is now available.

![](https://cloud.githubusercontent.com/assets/136959/26758094/09c59390-489a-11e7-9404-712ab8015e95.gif)
